# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Tests
run-name: Tests 🧪

on:
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.2
        env:
          POSTGRES_PASSWORD: test_db
          POSTGRES_USER: test_db
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: 🔨 Install dependencies
        run: pip install -r requirements.txt

      - name: ✅ Run unit tests
        run: pytest -vvv
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
